# Generated by Django 5.2.7 on 2025-11-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_body_alter_news_date_alter_news_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='image_url',
            field=models.URLField(verbose_name='URL картинки'),
        ),
    ]
