# Generated by Django 5.2.7 on 2025-11-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsimage_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_count', models.PositiveIntegerField(default=6, verbose_name='Кол-во новостей для парсинга')),
            ],
            options={
                'verbose_name': 'Настройка новостей',
                'verbose_name_plural': 'Настройки новостей',
            },
        ),
    ]
