# Generated by Django 5.2.7 on 2025-11-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_newsimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='crop_position',
            field=models.CharField(default='center', max_length=20, verbose_name='Позиция обрезки (object-position)'),
        ),
    ]
