# Generated by Django 5.2.7 on 2025-11-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsimage_crop_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='crop_position',
            field=models.CharField(choices=[('top', 'Сверху'), ('center', 'По центру'), ('bottom', 'Снизу'), ('0%', '0% сверху'), ('5%', '5% сверху'), ('10%', '10% сверху'), ('15%', '15% сверху'), ('20%', '20% сверху'), ('25%', '25% сверху'), ('30%', '30% сверху'), ('35%', '35% сверху'), ('40%', '40% сверху'), ('45%', '45% сверху'), ('50%', '50% сверху'), ('55%', '55% сверху'), ('60%', '60% сверху'), ('65%', '65% сверху'), ('70%', '70% сверху'), ('75%', '75% сверху'), ('80%', '80% сверху'), ('85%', '85% сверху'), ('90%', '90% сверху'), ('95%', '95% сверху'), ('100%', '100% сверху')], default='center', max_length=10, verbose_name='Позиция обрезки'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image_url',
            field=models.URLField(verbose_name='URL картинки'),
        ),
    ]
