# Generated by Django 5.2.7 on 2025-11-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_newsimage_crop_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='image_url',
            field=models.URLField(max_length=500, verbose_name='URL картинки'),
        ),
    ]
