# Generated by Django 5.2.7 on 2025-11-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_newsimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_body_edited',
            field=models.BooleanField(default=False, verbose_name='Текст отредактирован вручную'),
        ),
        migrations.AddField(
            model_name='news',
            name='is_title_edited',
            field=models.BooleanField(default=False, verbose_name='Заголовок отредактирован вручную'),
        ),
    ]
