# Generated by Django 5.2.7 on 2025-11-24 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='auto_title_sentences',
            field=models.PositiveSmallIntegerField(default=2, help_text='Число предложений для автоматического заголовка', verbose_name='Обрезать заголовок до N предложений (авто)'),
        ),
    ]
