# Generated by Django 5.2.7 on 2025-12-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_news_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('event_date_start', models.DateField(help_text='дд.мм.гггг', verbose_name='Дата начала')),
                ('event_date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('registration_deadline', models.DateField(blank=True, null=True, verbose_name='Дедлайн заявок')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Место проведения')),
                ('venue', models.CharField(blank=True, max_length=200, verbose_name='Площадка')),
                ('tags', models.CharField(blank=True, help_text='Через запятую: конференция, семинар, хакатон', max_length=500, verbose_name='Теги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
                'ordering': ['-event_date_start'],
            },
        ),
    ]
