# Generated by Django 5.2.7 on 2025-12-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_alter_event_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_start',
            field=models.DateField(help_text='дд.мм.гггг', verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн заявок'),
        ),
    ]
