# Generated by Django 5.2.7 on 2025-12-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_event_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date_end',
            field=models.DateTimeField(blank=True, help_text='Формат: дд.мм.гггг чч:мм', null=True, verbose_name='Дата и время окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date_start',
            field=models.DateTimeField(help_text='Формат: дд.мм.гггг чч:мм', verbose_name='Дата и время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='Формат: дд.мм.гггг чч:мм', null=True, verbose_name='Дедлайн заявок'),
        ),
    ]
