# Generated by Django 5.2.7 on 2026-02-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_event_event_date_end_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
