# Generated by Django 5.2.7 on 2026-02-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='ID поста'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=2000, verbose_name='Заголовок'),
        ),
    ]
