# Generated by Django 5.2.7 on 2025-12-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('city', models.CharField(blank=True, default='Не определено', max_length=100, null=True)),
                ('country', models.CharField(blank=True, default='Не определено', max_length=100, null=True)),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Посещения',
                'indexes': [models.Index(fields=['created_at'], name='core_visit_created_4d6338_idx'), models.Index(fields=['city'], name='core_visit_city_5d10a5_idx'), models.Index(fields=['ip_address', 'created_at'], name='core_visit_ip_addr_e7e042_idx')],
            },
        ),
    ]
