# Generated by Django 5.2.7 on 2025-12-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'verbose_name': 'Посещение', 'verbose_name_plural': 'Посещения'},
        ),
        migrations.AlterField(
            model_name='visit',
            name='city',
            field=models.CharField(blank=True, default='Не определено', max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='country',
            field=models.CharField(blank=True, default='Не определено', max_length=100, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата посещения'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='Сведения'),
        ),
    ]
