# Generated by Django 5.2.7 on 2026-02-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_visit_options_alter_visit_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('day1', models.PositiveIntegerField()),
                ('month1', models.CharField(max_length=20)),
                ('day2', models.PositiveIntegerField()),
                ('month2', models.CharField(max_length=20)),
                ('day3', models.PositiveIntegerField()),
                ('month3', models.CharField(max_length=20)),
                ('day4', models.PositiveIntegerField()),
                ('month4', models.CharField(max_length=20)),
                ('day5', models.PositiveIntegerField()),
                ('month5', models.CharField(max_length=20)),
                ('day6', models.PositiveIntegerField()),
                ('month6', models.CharField(max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('use_current_year', models.BooleanField(default=False, verbose_name='Авто-год (текущий)')),
            ],
            options={
                'verbose_name': 'Событие плана',
                'verbose_name_plural': 'События плана',
            },
        ),
    ]
