# Generated by Django 5.2.7 on 2026-02-04 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_planevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planevent',
            old_name='year',
            new_name='myyear',
        ),
    ]
