# Generated by Django 5.2.7 on 2026-02-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_year_planevent_myyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planevent',
            name='title',
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month1',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month2',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month3',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month4',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month5',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month6',
            field=models.TextField(max_length=20),
        ),
    ]
