# Generated by Django 5.2.7 on 2026-02-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_planevent_title_alter_planevent_month1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='planevent',
            options={'verbose_name': 'Даты проведения устного собеседования ', 'verbose_name_plural': 'Устное собеседование даты'},
        ),
    ]
