# Generated by Django 5.2.7 on 2026-02-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_planevent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planevent',
            name='myyear',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
