# Generated by Django 5.2.7 on 2026-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_planevent_myyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planevent',
            name='day1',
            field=models.PositiveIntegerField(verbose_name='День 1'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day2',
            field=models.PositiveIntegerField(verbose_name='День 2'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day3',
            field=models.PositiveIntegerField(verbose_name='День 3'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day4',
            field=models.PositiveIntegerField(verbose_name='День 4'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day5',
            field=models.PositiveIntegerField(verbose_name='День 5'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day6',
            field=models.PositiveIntegerField(verbose_name='День 6'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month1',
            field=models.TextField(max_length=20, verbose_name='Месяц 1'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month2',
            field=models.TextField(max_length=20, verbose_name='Месяц 2'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month3',
            field=models.TextField(max_length=20, verbose_name='Месяц 3'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month4',
            field=models.TextField(max_length=20, verbose_name='Месяц 4'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month5',
            field=models.TextField(max_length=20, verbose_name='Месяц 5'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month6',
            field=models.TextField(max_length=20, verbose_name='Месяц 6'),
        ),
    ]
