# Generated by Django 5.2.7 on 2026-02-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_planevent_day1_alter_planevent_day2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planevent',
            name='myyear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
