# Generated by Django 5.2.7 on 2026-02-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_planevent_myyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planevent',
            name='day1',
            field=models.PositiveIntegerField(blank=True, default='-', null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day2',
            field=models.PositiveIntegerField(blank=True, default='-', null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day3',
            field=models.PositiveIntegerField(blank=True, default='-', null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day4',
            field=models.PositiveIntegerField(blank=True, default='-', null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day5',
            field=models.PositiveIntegerField(blank=True, default='-', null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day6',
            field=models.PositiveIntegerField(blank=True, default='-', null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month1',
            field=models.TextField(blank=True, default='-', max_length=20, null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month2',
            field=models.TextField(blank=True, default='-', max_length=20, null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month3',
            field=models.TextField(blank=True, default='-', max_length=20, null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month4',
            field=models.TextField(blank=True, default='-', max_length=20, null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month5',
            field=models.TextField(blank=True, default='-', max_length=20, null=True, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='month6',
            field=models.TextField(blank=True, default='-', max_length=20, null=True, verbose_name='Месяц'),
        ),
    ]
