# Generated by Django 5.2.7 on 2026-02-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_planevent_day1_alter_planevent_day2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planevent',
            name='day1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='День'),
        ),
        migrations.AlterField(
            model_name='planevent',
            name='day6',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='День'),
        ),
    ]
