# Generated by Django 5.2.7 on 2025-12-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
                ('graduation_year', models.IntegerField(verbose_name='Год выпуска')),
                ('graduation_month', models.CharField(default='Май', max_length=20, verbose_name='Месяц выпуска')),
                ('specialization', models.CharField(max_length=300, verbose_name='Направление производственной деятельности')),
                ('photo', models.ImageField(upload_to='graduates/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Выпускник',
                'verbose_name_plural': 'Выпускники',
                'ordering': ['-graduation_year', 'full_name'],
            },
        ),
    ]
