# Generated by Django 5.2.7 on 2025-12-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='graduates/', verbose_name='Фото'),
        ),
    ]
