# Generated by Django 5.2.7 on 2025-12-14 14:42

import halloffame.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0002_alter_graduate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='graduation_month',
            field=models.CharField(default=halloffame.models.current_month_name_ru, max_length=20, verbose_name='Месяц выпуска'),
        ),
    ]
