# Generated by Django 5.2.7 on 2026-03-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0003_alter_graduate_graduation_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='status',
            field=models.CharField(blank=True, help_text="Например: Работает в ПАО 'Газпром'", max_length=1000, null=True, verbose_name='Статус'),
        ),
    ]
