# Generated by Django 5.2.7 on 2026-03-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0004_graduate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Достижения'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='contacts',
            field=models.TextField(blank=True, help_text='Телефон, Почта, Ссылка на портфолио', null=True, verbose_name='Контакты'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='current_work_place',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Текущее место работы'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='key_skills',
            field=models.TextField(blank=True, help_text='Например: Python, SQL, Project Management', null=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='scientific_supervisor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Научный руководитель'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='vkr_theme',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Тема ВКР/диплома'),
        ),
    ]
