# Generated by Django 5.2.7 on 2026-03-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0005_graduate_achievements_graduate_contacts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='current_work_place',
        ),
        migrations.AlterField(
            model_name='graduate',
            name='contacts',
            field=models.TextField(blank=True, help_text='Телефон, Почта, Соцсети', null=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='О выпускнике (биография)'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='key_skills',
            field=models.TextField(blank=True, help_text='Введите через запятую: Python, SQL, CRM', null=True, verbose_name='Ключевые навыки'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='specialization',
            field=models.CharField(max_length=300, verbose_name='Направление деятельности'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='status',
            field=models.CharField(blank=True, help_text="Например: ПАО 'Газпром', ведущий инженер", max_length=300, null=True, verbose_name='Текущее место работы'),
        ),
    ]
