# Generated by Django 5.2.7 on 2026-03-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0006_remove_graduate_current_work_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='current_work_place',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Текущее место работы'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='status',
            field=models.CharField(default=1, help_text='Выпускник / Аспирант / Магистрант', max_length=100, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
