# Generated by Django 5.2.7 on 2026-03-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0007_graduate_current_work_place_alter_graduate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='short_info',
            field=models.TextField(blank=True, help_text='Отображается в карточке в специальном блоке', max_length=500, null=True, verbose_name='Коротко о выпускнике'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Полная биография'),
        ),
    ]
