# Generated by Django 5.2.7 on 2026-03-07 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0008_graduate_short_info_alter_graduate_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='contacts',
        ),
        migrations.AlterField(
            model_name='graduate',
            name='description',
            field=models.TextField(blank=True, help_text='Отображается в модальном окне', null=True, verbose_name='Полная биография'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='short_info',
            field=models.TextField(blank=True, help_text='Отображается в карточке в стеклянном блоке', max_length=500, null=True, verbose_name='Коротко о выпускнике'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='status',
            field=models.CharField(help_text='Например: Выпускник / Аспирант / Магистрант', max_length=100, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='GraduateContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('text', 'Просто текст (Телефон, адрес)'), ('link', 'Ссылка (Сайт, Портфолио)'), ('social', 'Текст + Ссылка (Телеграм, ВК)')], default='text', max_length=10, verbose_name='Тип контакта')),
                ('label', models.CharField(help_text="Например: 'Телеграм' или номер телефона", max_length=100, verbose_name='Заголовок/Текст')),
                ('url', models.URLField(blank=True, help_text='Обязательно с http:// или https://', null=True, verbose_name='Ссылка')),
                ('graduate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_set', to='halloffame.graduate', verbose_name='Выпускник')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
