# Generated by Django 5.2.7 on 2026-03-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halloffame', '0009_remove_graduate_contacts_alter_graduate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatecontact',
            name='label',
            field=models.CharField(blank=True, help_text="Например: 'Телеграм' или номер телефона", max_length=100, null=True, verbose_name='Заголовок/Текст'),
        ),
    ]
